import React from 'react'
import type { AppSettings } from '@shared/types.js'
import type { ExtensionAction } from '@shared/api.js'
import type { ExtensionStatus } from '@shared/extension/protocol.js'
import { validQuickApply, quickPrice } from '@shared/quickApply.js'
import { rased } from '../api.js'
export function QuickApplySettings({settings}:{settings:AppSettings}):React.ReactElement {
  const ar=settings.language==='ar'
  const [draft,setDraft]=React.useState({...settings.quickApply})
  const [status,setStatus]=React.useState<ExtensionStatus|null>(null)
  const [message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false)
  const [label,setLabel]=React.useState(ar?'بروفايل Chrome الرئيسي':'Main Chrome profile')
  React.useEffect(()=>setDraft({...settings.quickApply}),[settings.quickApply])
  React.useEffect(()=>{void rased.getExtensionStatus().then(setStatus).catch(()=>setMessage(ar?'تعذر الاتصال':'Connection failed'));return rased.onExtensionStatus(setStatus)},[ar])
  const ready=!!status?.registered&&!!status?.selectedId
  const act=async(action:ExtensionAction)=>{setBusy(true);try{const result=await rased.extensionAction(action);setStatus(await rased.getExtensionStatus());setMessage(result.ok?(ar?'تم':'Done'):(ar?'تعذر إتمام الخطوة. تأكد أن Chrome مثبت ثم أعد المحاولة.':'Unable to complete this step. Check Chrome installation and retry.'))}catch{setMessage(ar?'تعذر الاتصال':'Connection failed')}finally{setBusy(false)}}
  const save=async()=>{setBusy(true);try{await rased.updateSettings({quickApply:draft});setMessage(ar?'تم الحفظ':'Saved')}catch{setMessage(ar?'راجع القالب والقيم وربط الإضافة':'Check template, values, and extension pairing')}finally{setBusy(false)}}
  const phases:Record<string,string>=ar?{'waiting-client':'في انتظار بروفايل Chrome المختار','opening':'فتح المشروع','reading':'قراءة النموذج','ready':'المسودة جاهزة — راجعها وقدم بنفسك','needs-input':'أكمل السعر أو المدة يدويًا','needs-login':'سجّل دخولك بالموقع ثم أعد المحاولة','draft-exists':'تركنا المسودة الموجودة كما هي','failed':'تعذر التجهيز، أعد المحاولة من المشروع','cancelled':'أُلغي التجهيز','expired':'انتهت المهلة — افتح البروفايل المختار وأعد المحاولة'}:{}
  return <section className="set-group">
    <h2>{ar?'التقديم السريع':'Quick Apply'}</h2>
    {status?.error&&<p className="field-err" role="alert">{ar?'تعذر تجهيز الاتصال المحلي. جرّب إصلاح الملفات، ثم إعادة تشغيل راصد، وراجع صلاحيات مجلد بيانات التطبيق.':'Local bridge unavailable. Repair extension files, restart RASED, and check app data folder permissions.'}</p>}
    <p className="hint">{ar?'لمستقل ونفذلي فقط. تستخدم الإضافة حساباتك داخل Chrome، وتجهز مسودة دون الضغط على تقديم. خمسات غير مشمول.':'Mostaql and Nafezly only. The extension uses your normal Chrome sessions and prepares a draft without submitting. Khamsat is excluded.'}</p>
    <ol className="quick-setup-steps">
      <li><h3>{ar?'تجهيز الإضافة':'Prepare the extension'} {status?.registered?'✓':''}</h3><p className="hint">{ar?'نحفظ ملفات الإضافة والربط المحلي في مجلد ثابت على جهازك. لا تحتاج تثبيت Node.js.':'Files and the local bridge are stored in a stable folder on your device. No Node.js installation needed.'}</p><button className="btn" disabled={busy} onClick={()=>void act({action:'prepare'})}>{ar?'تجهيز / إصلاح ملفات الإضافة':'Prepare / repair extension files'}</button></li>
      <li><h3>{ar?'تثبيت في بروفايل Chrome':'Install in your Chrome profile'}</h3><p className="hint">{ar?'افتح إضافات Chrome في البروفايل الذي تستخدمه للمواقع، فعّل وضع المطوّر، واضغط تحميل إضافة غير مضغوطة، ثم اختر المجلد التالي. هذه خطوة يدوية مرة واحدة لكل بروفايل.':'Open Chrome extensions in your preferred profile, enable Developer mode, choose Load unpacked, and select the folder below. This is a manual step once per profile.'}</p><code dir="ltr">{status?.folder??'…'}</code><div className="row-actions"><button className="btn sm" disabled={busy||!status?.installed} onClick={()=>void act({action:'copy-path'})}>{ar?'نسخ المسار':'Copy path'}</button><button className="btn sm" disabled={busy||!status?.installed} onClick={()=>void act({action:'folder'})}>{ar?'فتح المجلد':'Open folder'}</button><button className="btn sm" disabled={busy} onClick={()=>void act({action:'chrome-extensions'})}>{ar?'فتح إضافات Chrome':'Open Chrome extensions'}</button></div></li>
      <li><h3>{ar?'ربط واختيار البروفايل':'Pair and select a profile'} {ready?'✓':''}</h3><p className="hint">{ar?'افتح أيقونة RASED في إضافات Chrome واضغط طلب الربط. طابق الرمز الظاهر هناك مع الرمز هنا قبل الموافقة.':'Open the RASED extension popup and request pairing. Match its code with the code here before approving.'}</p>
        {status?.pairing.map(p=><div key={p.id}><strong dir="ltr">{p.code}</strong><label>{ar?'اسم البروفايل':'Profile label'}<input className="input" maxLength={60} value={label} onChange={e=>setLabel(e.target.value)}/></label><button className="btn" disabled={busy||!label.trim()} onClick={()=>{if(window.confirm(ar?`هل الرمز في الإضافة هو ${p.code}؟`:`Does the extension show ${p.code}?`))void act({action:'approve',id:p.id,code:p.code,label})}}>{ar?'مطابقة الرمز والموافقة':'Match code and approve'}</button></div>)}
        {!!status?.clients.length&&<label>{ar?'البروفايل المستخدم للتقديم':'Profile used for Quick Apply'}<select className="select" value={status.selectedId??''} disabled={busy} onChange={e=>void act({action:'select',id:e.target.value})}><option value="" disabled>{ar?'اختر بروفايل':'Choose profile'}</option>{status.clients.map(p=><option key={p.id} value={p.id}>{p.label} · {p.connected?(ar?'متصل':'connected'):(ar?'غير متصل':'offline')} · {p.version}</option>)}</select></label>}
        {status?.selectedId&&<button className="btn sm ghost" disabled={busy} onClick={()=>{if(window.confirm(ar?'إلغاء ربط البروفايل؟ لن نحذف تسجيل دخولك بالمواقع.':'Unpair this profile? Website sessions will remain.'))void act({action:'revoke',id:status.selectedId!})}}>{ar?'إلغاء الربط':'Unpair'}</button>}
      </li>
    </ol>
    <p className="hint">{ar?'إذا كان Chrome مغلقًا نحاول فتحه وننتظر البروفايل المختار 20 ثانية. قد يفتح Chrome بروفايلًا مختلفًا؛ افتح المختار وأعد المحاولة بعد انتهاء المهلة. بعد تحديث الإضافة اضغط إعادة تحميل في صفحة إضافات Chrome.':'If Chrome is closed, RASED opens it and waits 20 seconds for the selected profile. Chrome may open a different profile; open yours and retry after a timeout. Reload the extension in Chrome after extension updates.'}</p>
    <label className="set-row"><span>{ar?'تفعيل التقديم السريع':'Enable Quick Apply'}</span><input type="checkbox" checked={draft.enabled} disabled={!ready} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/></label>
    <label htmlFor="quick-template">{ar?'نص العرض المحفوظ':'Saved proposal text'}</label><textarea id="quick-template" className="input" rows={9} maxLength={10000} dir="auto" value={draft.template} onChange={e=>setDraft({...draft,template:e.target.value})}/>
    <label className="set-row"><span>{ar?'موضع السعر داخل الميزانية (%)':'Position within budget (%)'}</span><input className="input" type="number" min={0} max={100} step={1} value={draft.budgetPositionPercent} onChange={e=>setDraft({...draft,budgetPositionPercent:e.target.valueAsNumber})}/></label>
    <input aria-label={ar?'موضع السعر':'Budget position'} type="range" min={0} max={100} step={1} value={Number.isFinite(draft.budgetPositionPercent)?draft.budgetPositionPercent:0} onChange={e=>setDraft({...draft,budgetPositionPercent:Number(e.target.value)})}/>
    <label className="set-row"><span>{ar?'أيام إضافية فوق مدة العميل':'Extra days beyond client duration'}</span><input className="input" type="number" min={0} max={365} step={1} value={draft.extraDays} onChange={e=>setDraft({...draft,extraDays:e.target.valueAsNumber})}/></label>
    <p className="hint">{ar?'مثال: ميزانية 25–50 دولارًا، مدة 5 أيام →':'Example: $25–50 budget, 5 days →'} <b>{quickPrice(25,50,draft.budgetPositionPercent)??'—'} USD / {Number.isInteger(draft.extraDays)?5+draft.extraDays:'—'} {ar?'أيام':'days'}</b></p>
    <button className="btn primary" disabled={busy||!validQuickApply(draft)} onClick={()=>void save()}>{ar?'حفظ القالب والإعدادات':'Save template and settings'}</button>
    {status?.lastJob&&<p role="status">{phases[status.lastJob.phase]??status.lastJob.phase} <button className="btn sm" disabled={busy} onClick={()=>void act({action:'cancel'})}>{ar?'إلغاء التجهيز':'Cancel preparation'}</button></p>}
    <p className="hint">{ar?'0% للحد الأدنى و100% للحد الأعلى. البيانات الناقصة تُدخل يدويًا؛ المسودة الموجودة لا تُستبدل. القالب يدخل في تصدير الإعدادات؛ مفاتيح الربط لا تدخل فيه.':'0% selects the minimum and 100% the maximum. Missing values require manual input; existing drafts are preserved. Settings exports include the template but exclude pairing keys.'}</p><p role="status">{message}</p>
  </section>
}
