// Narrow, typed IPC surface. The renderer never sees Node, SQL or fetch.
// Every channel used by the renderer MUST be listed here exactly once.
export const IPC = {
  getProjects: 'rased:get-projects',
  getProjectCount: 'rased:get-project-count',
  setReadState: 'rased:set-read-state',
  markAllRead: 'rased:mark-all-read',
  getSettings: 'rased:get-settings',
  updateSettings: 'rased:update-settings',
  getHealth: 'rased:get-health',
  pause: 'rased:pause',
  resume: 'rased:resume',
  refresh: 'rased:refresh',
  openProject: 'rased:open-project',
  openProjectExternal: 'rased:open-project-external',
  getDiagnostics: 'rased:get-diagnostics',
  // v2: personal data, details, saved filters, DND, data, compact
  getProject: 'rased:get-project',
  getProjectDetails: 'rased:get-project-details',
  requestProjectDetails: 'rased:request-project-details',
  updateProjectUserState: 'rased:update-project-user-state',
  getSavedFilters: 'rased:get-saved-filters',
  createSavedFilter: 'rased:create-saved-filter',
  updateSavedFilter: 'rased:update-saved-filter',
  deleteSavedFilter: 'rased:delete-saved-filter',
  previewFilterCount: 'rased:preview-filter-count',
  queryProjectsPage: 'rased:query-projects-page',
  testNotification: 'rased:test-notification',
  openWindowsNotificationSettings: 'rased:open-windows-notification-settings',
  testSound: 'rased:test-sound',
  setDnd: 'rased:set-dnd',
  openDataFolder: 'rased:open-data-folder',
  exportSettings: 'rased:export-settings',
  validateImport: 'rased:validate-import',
  applyImport: 'rased:apply-import',
  purgeHistoryPreview: 'rased:purge-history-preview',
  purgeHistoryApply: 'rased:purge-history-apply',
  openCompact: 'rased:open-compact',
  closeCompact: 'rased:close-compact',
  setAlwaysOnTop: 'rased:set-always-on-top',
  showProjectInMain: 'rased:show-project-in-main',
  windowControl: 'rased:window-control',
  getWindowState: 'rased:get-window-state',
  windowState: 'rased:window-state',
  getAppInfo: 'rased:get-app-info',
  openAboutLink: 'rased:open-about-link',
  confirmClose: 'rased:confirm-close',
  getUpdateState: 'rased:get-update-state',
  checkUpdate: 'rased:check-update',
  downloadUpdate: 'rased:download-update',
  installUpdate: 'rased:install-update',
  confirmUpdateInstall: 'rased:confirm-update-install',
  updateState: 'rased:update-state',
  requestUpdateInstall: 'rased:request-update-install',
  // main -> renderer events
  projectsChanged: 'rased:projects-changed',
  healthChanged: 'rased:health-changed',
  settingsChanged: 'rased:settings-changed',
  detailsChanged: 'rased:details-changed',
  navigate: 'rased:navigate',
  requestClose: 'rased:request-close',
  openSettings: 'rased:open-settings',
  playBeep: 'rased:play-beep'
} as const
