// Offline, versioned product disclosures. No forced consent or license restrictions.
type LegalDocument = { title: string; sections: [string, string][] }
export const LEGAL_UPDATED_AT = '2026-09-28'
export const LEGAL_DOCUMENTS: Record<'ar'|'en', Record<'terms'|'privacy'|'licenses',LegalDocument>> = {
  ar: {
    terms: {title:'شروط الاستخدام',sections:[
      ['وظيفة البرنامج','راصد أداة محلية لمتابعة خلاصة RSS العامة لمستقل، وتنظيم المشاريع وإظهار التنبيهات. قد يطلب صفحات التفاصيل العامة لإكمال المعلومات. تقديم العروض والتعاقد والدفع يتم بواسطتك على مستقل؛ البرنامج لا يدخل حسابك ولا يرسل عروضًا آلية.'],
      ['علاقة المنصة وحقوق المحتوى','مستقل وحسوب وعلاماتهما ومحتوى المشاريع تخص أصحابها. ظهور محتوى عام أو وجود RSS ليس تصريحًا بإعادة نشره أو بجلب آلي غير محدود. لا تمنح هذه الصفحات إذنًا من المنصة. احترم شروط المصدر والقيود المحلية وحقوق أصحاب المحتوى؛ لا تستخدم راصد لتجاوز الحماية أو جمع معلومات خاصة أو إعادة بيع محتوى المشاريع.'],
      ['استخدام مسؤول','لا تتحايل على حظر أو تحدي حماية، ولا تعدّل البرنامج لإغراق المصدر بطلبات أو إساءة استخدام المنصة. يتبع البرنامج التهدئة عند الرفض والأخطاء. قد تقيّد المنصة الوصول أو تغيّر شروطها. ترخيص الكود لا يعفي مستخدمه أو موزعه من الحصول على أذونات المصدر المطلوبة.'],
      ['الدقة والتنبيهات','المعلومات قد تكون ناقصة أو قديمة، وقد تتأخر التنبيهات أو لا تصل. راجع المشروع الأصلي قبل تقديم عرض أو اتخاذ قرار. لا نضمن الرصد اللحظي أو السبق أو قبول العروض أو استمرار الخدمة.'],
      ['مساعد العروض','في النسخة التطويرية يمكنك طلب مسودة عرض من Gemini بعد معاينة البيانات والموافقة على إرسالها. راجع المسودة وعدّلها قبل نسخها وتقديمها بنفسك على مستقل؛ قد تكون غير دقيقة أو تتضمن خبرات أو وعودًا لم تقدمها. لا ينشئ راصد حساب مستقل ولا يقدم عروضًا آليًا. استخدام Gemini ومفتاحك يخضع لشروط Google، ومنها متطلبات السن والمنطقة والخطة المتاحة: https://ai.google.dev/gemini-api/terms . ولا تمنح هذه الميزة حقوقًا إضافية في محتوى المشاريع.'],
      ['الترخيص والمسؤولية','الكود متاح وفق MIT ونصها الأصلي في قسم الرخص. البرنامج مقدم كما هو، دون ضمانات في الحدود التي يسمح بها القانون؛ لا تُلغى حقوق إلزامية للمستخدم أو مسؤوليات لا يجوز استبعادها. هذه المعلومات لا تحل محل استشارة قانونية ولا تمثل اعتمادًا قانونيًا للبرنامج.'],
      ['التحديث والتواصل','مساعد العروض متاح في نسخة التطوير الحالية، وليس في الإصدار المنشور 0.2.6. راجع النص عند الترقية. للبلاغات المتعلقة بالكود أو الحقوق استخدم مستودع GitHub أو LinkedIn للمطور. لا تنشر بيانات حساسة في البلاغات العامة.']
    ]},
    privacy: {title:'الخصوصية',sections:[
      ['ما يبقى على جهازك','تُحفظ المشاريع والمقتطفات والوصف المجلوب، حالة القراءة والمحفوظات والملاحظات والفلاتر والإعدادات والسجل التشخيصي محليًا في SQLite ومجلد بيانات التطبيق. لا يوجد حساب راصد أو خادم سحابي أو تحليلات أو رفع آلي لهذه البيانات للمطور في هذا الإصدار.'],
      ['الاتصالات الخارجية','يتصل جهازك مباشرة بمستقل لجلب RSS وصفحات التفاصيل عند الحاجة؛ قد يرى الموقع ومزود الشبكة عنوان IP ووقت الطلب وبيانات الاتصال وUser-Agent. فتح رابط مشروع أو GitHub أو LinkedIn يشغّل متصفحك وتطبق سياسات تلك المواقع. لا يقرأ راصد جلسة المتصفح أو كلمات مرور مستقل.'],
      ['مساعد العروض وGemini','ميزة التطوير الاختيارية لا تجري طلبًا عند الرصد أو فتح المشروع. بعد معاينة البيانات وتحديد الموافقة والضغط على «توليد» فقط، يرسل جهازك مباشرة إلى Google Gemini عنوان المشروع ووصفه المتاح ومصدر اكتماله وتصنيفه ومهاراته وميزانيته وبيانات الملف المهني التي تحفظها ونصًا إضافيًا تكتبه لهذا العرض. لا تُرسل ملاحظتك الشخصية المحفوظة على المشروع تلقائيًا. يعود رد بمسودة وافتراضات وأسئلة وتُحفظ المسودة محليًا في SQLite، ويمكنك تعديلها أو حذفها. قد يصل Google عنوان IP وبيانات الطلب والمدخلات والمخرجات. لا ترسل معلومات سرية أو شخصية إلا إذا كنت مخولًا بمشاركتها. الإصدار المنشور 0.2.6 لا يحتوي هذه الميزة.'],
      ['كيفية تعامل Google مع بيانات Gemini','وفق شروط Gemini API، تستخدم Google مدخلات ومخرجات الخدمات غير المدفوعة لتحسين منتجاتها وتقنياتها، وقد يطلع عليها مراجعون بشريون؛ وتنصح Google بعدم إرسال معلومات حساسة أو سرية أو شخصية عبرها. في الخدمات المدفوعة المرتبطة بحساب فوترة نشط لا تستخدم Google المدخلات والمخرجات لتحسين منتجاتها، لكنها تحتفظ بسجلات محدودة لمنع إساءة الاستخدام. توجد استثناءات وقيود إقليمية، ومنها ترتيبات مختلفة للمنطقة الاقتصادية الأوروبية والمملكة المتحدة وسويسرا. راجع الشروط السارية على حسابك قبل الاستخدام: https://ai.google.dev/gemini-api/terms .'],
      ['مفتاح Gemini والتكلفة','يضع المستخدم مفتاح Gemini الخاص به؛ لا يقدّم راصد مفتاحًا مشتركًا. يُخزن المفتاح مشفرًا محليًا باستخدام حماية Windows، منفصلًا عن قاعدة المشاريع وملفات تصدير الإعدادات، ويمكن حذفه. هذا لا يحميه من برامج تعمل بنفس حساب Windows. الاستخدام والحصص وأي رسوم تحددها Google وخطة حسابك. لا يُضمّن المفتاح في المسودات أو السجلات أو ملفات الدعم.'],
      ['تحديثات البرنامج','تتصل نسخة Windows المجمّعة بـ GitHub ومضيفي ملفات الإصدارات تلقائيًا عند التشغيل وكل 6 ساعات للتحقق من التحديثات، وباختيارك لتحميلها. قد تستقبل هذه الخدمات عنوان IP ومعلومات الاتصال والطلب؛ لا تُرسل قاعدة المشاريع أو الملاحظات أو الفلاتر. ملف التحديث يُحفظ في ذاكرة تخزين مؤقت محلية. التثبيت بطلبك ويعيد تشغيل التطبيق، ولا يحدث بمجرد إغلاقه.'],
      ['أمان التخزين والإشعارات','قاعدة البيانات والنسخ الاحتياطية ليست مشفرة على مستوى التطبيق. من يستطيع الوصول إلى حساب Windows أو ملفاتك قد يقرأها. قد تظهر عناوين المشاريع في إشعارات Windows وسجل النظام؛ يمكنك تعطيل التنبيهات والصوت أو استخدام عدم الإزعاج. لا تضع كلمات مرور أو معلومات حساسة في الملاحظات.'],
      ['الحذف والنسخ الاحتياطية','من الإعدادات → البيانات تستطيع حذف السجل غير المحمي؛ يحافظ الحذف على المحفوظات والملاحظات ومسودات العروض وحالات الاهتمام/التقديم وينشئ نسخة احتياطية قبل الحذف. إزالة البرنامج لا تعني حذف بياناته تلقائيًا. للحذف الكامل أغلق راصد من Tray، وافتح مجلد البيانات واحذف ملفاته والنسخ الاحتياطية بنفسك إذا لم تعد تحتاجها؛ قد يبقى سجل إشعارات Windows أو نسخ النظام الاحتياطية خارج تحكم التطبيق.'],
      ['المشاركة الاختيارية','تصدير الإعدادات أو إرسال لقطة شاشة أو سجل للدعم يتم باختيارك، وقد يكشف فلاترك أو عناوين المشاريع أو مسارات ملفات محلية. راجع الملف وأخفِ المعلومات الخاصة قبل مشاركته. بلاغات GitHub عامة؛ لا ترسل معلومات حساسة فيها.']
    ]},
    licenses: {title:'الرخص والحقوق',sections:[
      ['الكود والمحتوى','MIT تخص كود راصد وتسمح باستخدامه وتعديله وتوزيعه مع حفظ إشعار الحقوق والنص. لا تنقل إليك ملكية محتوى مستقل أو تمنح موافقته على الجلب، ولا تجعل راصد منتجًا رسميًا للمنصة.'],
      ['المكونات','تُرفق نصوص رخص مكونات JavaScript والخطوط أدناه؛ توزيع Electron يضم LICENSE.electron.txt وLICENSES.chromium.html للمكونات المدمجة. احتفظ بهذه الإشعارات عند التوزيع. شعار راصد المتجهي مرفق ضمن ملفات المشروع؛ لا نؤكد تسجيله علامة تجارية.']
    ]}
  },
  en: {
    terms: {title:'Terms of use',sections:[
      ['Purpose','RASED is a local tool for following the public Mostaql RSS feed, organizing projects and showing alerts. It may fetch public detail pages to complete information. You submit proposals, contract and pay on Mostaql yourself. RASED does not access your account or submit automated proposals.'],
      ['Platform and content rights','Mostaql, Hsoub, their marks and project content belong to their respective owners. Public availability or an RSS feed does not establish permission for republication or unrestricted automated access. These documents do not grant platform permission. Respect source terms, applicable law and content rights; do not bypass protection, collect private information or resell project content.'],
      ['Responsible use','Do not evade blocks or challenges, flood the source, or abuse the platform. The application applies backoff on rejection and errors. The platform may restrict access or change its terms. The code license does not replace source permissions required by users or distributors.'],
      ['Accuracy and alerts','Information may be incomplete or stale and alerts may be delayed or missed. Check the original project before submitting a proposal or making decisions. Instant discovery, priority over competitors, successful proposals and continued availability are not guaranteed.'],
      ['Proposal Assistant','In the development build you can ask Gemini to draft a proposal after previewing and approving the data sent. Review and edit the draft before copying and submitting it yourself on Mostaql; it can contain mistakes, invented experience or unsupported promises. RASED does not create a Mostaql account or submit proposals automatically. Use of Gemini and your key is subject to Google terms, including age, regional and service-tier restrictions: https://ai.google.dev/gemini-api/terms . This feature grants no additional rights to project content.'],
      ['License and liability','The software is provided under MIT, reproduced in Licenses. It is provided as is, without warranties to the extent permitted by law; mandatory consumer rights and liabilities that cannot legally be excluded remain unaffected. These disclosures are not legal advice or certification of compliance.'],
      ['Updates and contact','The Proposal Assistant is available in the current development build, not in published version 0.2.6. Review the text after upgrades. Contact the developer through the GitHub repository or LinkedIn for code or rights concerns. Do not post sensitive information in public reports.']
    ]},
    privacy: {title:'Privacy',sections:[
      ['Local data','Projects, excerpts, fetched descriptions, read states, bookmarks, notes, filters, settings and diagnostics are stored locally in SQLite and the application data folder. This version has no RASED account, cloud backend, analytics or automatic upload of this data to the developer.'],
      ['External connections','Your device contacts Mostaql directly for RSS and detail pages as needed. The site and network providers may receive your IP address, request timing, connection metadata and User-Agent. Project, GitHub and LinkedIn links open in your browser and those sites apply their own policies. RASED does not read your browser session or Mostaql password.'],
      ['Proposal Assistant and Gemini','The optional development feature makes no AI request while watching or merely opening a project. Only after you preview data, check consent and press Generate does your device send the project title, available description and completeness, category, skills, budget, saved freelancer profile and any notes entered for this proposal directly to Google Gemini. Your saved private project note is not included automatically. Gemini returns a draft, assumptions and questions; the draft is stored in local SQLite and can be edited or deleted. Google may receive your IP address, request metadata, input and output content. Do not include personal or confidential information unless authorized. Published version 0.2.6 has no Proposal Assistant.'],
      ['How Google handles Gemini data','Under the Gemini API terms, Google uses unpaid-service inputs and outputs to improve its products and technologies, and human reviewers may examine them; Google advises against sending sensitive, confidential or personal information through unpaid services. For paid services associated with an active billing account, Google does not use inputs and outputs to improve its products, but retains limited abuse-prevention logs. Regional exceptions and restrictions apply, including different treatment for the EEA, UK and Switzerland. Review the terms applicable to your account: https://ai.google.dev/gemini-api/terms .'],
      ['Gemini key and cost','Users provide their own Gemini key; RASED supplies no shared key. The key is stored locally with Windows-backed encryption, outside the project database and settings exports, and can be deleted. This does not protect it from software running as the same Windows user. Google and your account tier determine quotas and any charges. The key is not included in drafts, logs or support files.'],
      ['Software updates','Packaged Windows builds automatically contact GitHub and release-asset hosts at startup and every 6 hours to check for updates, and on your request to download them. These services may receive your IP and request/connection metadata; projects, notes and filters are not uploaded. Downloads are cached locally. Installation requires your request and restarts the app; merely quitting does not install an update.'],
      ['Storage and notifications','The database and backups have no application-level encryption. Someone with access to your Windows account or files may read them. Project titles may appear in Windows notifications and system history. Disable notifications, mute sound or enable DND as needed; do not put passwords or sensitive data in notes.'],
      ['Deletion and backups','Settings → Data can purge unprotected history; bookmarked/noted projects, proposal drafts and interested/submitted statuses are retained, and a backup is created before deletion. Uninstalling does not automatically delete application data. For full removal, quit RASED from the tray, open its data folder and delete its files and backups yourself if no longer needed. Windows notification history and system backups are outside the application’s control.'],
      ['Optional sharing','Exporting settings or sending screenshots or diagnostics is your choice and may disclose filters, project titles or local file paths. Review and redact files before sharing. GitHub reports are public; do not include sensitive information.']
    ]},
    licenses: {title:'Licenses & rights',sections:[
      ['Software versus content','MIT covers RASED code and allows use, modification and distribution with its copyright and license notice. It does not grant ownership of Mostaql content or permission to collect it, and does not imply endorsement.'],
      ['Components','JavaScript and font license texts are included below. Electron distributions also carry LICENSE.electron.txt and LICENSES.chromium.html for bundled components. Preserve these notices when distributing. The project includes its compass SVG; no registered trademark claim is made.']
    ]}
  }
}
